file1=open("sample.txt","w")
file1.write("Hello World")
file1.close()
file1=open("sample.txt","w")
file1.write("Hello India")
file1.close()
file1=open("sample.txt","r")
content=file1.read()
print(content)
file1.close()
