file1=open("Xyz.java","w")
file1.write("Hello World")
file1.close()
file1=open("Xyz.java","w")
file1.write(" ")
file1.close()
file1=open("Xyz.java","r")
content=file1.read()
print(content)
file1.close()
